### ISSUE TITLE
에러 리포팅

### ISSUE THREAD

**Issue by cece-09** [cece-09/BobBuddy_frontend#50]
클라이언트에서 에러 발생 시 fallback UI 구현합니다.
리포팅 필요한 경우 서버로 보내도록 합니다.
* 서드파티 관련 에러
* 클라이언트 로직 에러

**Comment by cece-09** [comment]
### 할 일

- [x] 1. handleError 유틸에서 리포팅 -> 로깅도 하면 좋을듯.. 일단 부가적인걸로
- [x] 2. 모달 컴포넌트(전역상태), 페이지 기본 레이아웃, 토스트 UI
- [ ] 3. 최최종 떨어지는 ErrorPage : LoadingPage로 통일
           떨어진 Error가 우리 에러가 아닌 경우.. UNKNOWN_ERROR 등으로 리포팅 할 수도
- [ ] 4. 소프트한 에러 처리 구현.. 컴포넌트 곳곳에서..
          * ErrorBoundary 기반 error.tsx는 onClick event에 따른 에러를 처리 못함
          * 아예 next에서 해주는 ErrorBoundary 말고 전역 에러 상태를 둬서 직접 setError 해줘도 될듯 -> UI에 띄워줘야 하는 에러를 set
- [ ] 5. 요청 타임아웃 에러 -> request 쪽에 한 번에 추가하고 error report는 그냥 fetch로 처리
- [ ] 6. Next에서 띄우는 클라이언트 어플리케이션.. 에러 어쩌구 페이지 삭제할 수 있는지 보기

**Comment by kimfield98** [comment]
6. 클라이언트 어플리케이션 어쩌구 페이지는 error.tsx로 커스텀해서 사용하고 있습니다! 홈으로 이동하기 버튼을 만들어서 임시처리만 했는데 더 좋은 방법이 있는지는 모르겠네요 ..!

**Comment by cece-09** [comment]
> 6. 클라이언트 어플리케이션 어쩌구 페이지는 error.tsx로 커스텀해서 사용하고 있습니다! 홈으로 이동하기 버튼을 만들어서 임시처리만 했는데 더 좋은 방법이 있는지는 모르겠네요 ..!

아하 이미 있었군요,, 그렇담 고 페이지를 전역으로 옮기는 건 어떤가용?? 페이지별로 에러 처리가 따로 되어야 하는 경우가..아직은 잘 생각나진 않아서..

이거는 사실 에러 발생 시 어떻게 해야 하는지 스펙 논의가 필요한 부분이긴 해서 의견 공유 받아보는 것도 좋을 것 같네요. 이번 주말 토픽에 추가해두겠습니당

**Comment by kimfield98** [comment]
우리 프로젝트에도 app > error.tsx가 있는데 이미 처리를 해두신 것 같은데요?! 아직도 어플리케이션 어쩌구 에러 화면이 보이나요? 그렇담 진짜 찾아봐야 함 ... (머쓱)
개인적인 이슈로는 4월 풀근무(야근+휴일)를 통보받아서 우리 이번 주 금요일 약속.. 일찍 회사를 나갈 수 있을지 모르겠어요🥹
(빨라도 9시 반이나 10시에 가능할 것 같은데 시간을 조정할 수 있나요 또르르)

**Comment by cece-09** [comment]
6은 다른 이슈로 분리하고, 본 이슈는 닫습니다.
