### ISSUE TITLE
ShadCN ui 의존성에 추가

### ISSUE THREAD

**Issue by cece-09** [cece-09/BobBuddy_frontend#60]

**Comment by kimfield98** [comment]
오늘 로그인, 회원가입, 프로필 페이지 shadcn 적용 후 pr 올리겠습니다요

**Comment by kimfield98** [comment]
shadcn/ui 쓰려면 tailwind를 다시 설치해야 된다고 하네요 .. 바꾸는 과정이 꽤나 까다로울 것 같아요 허허

**Comment by cece-09** [comment]
이런스... 보시기에 tailwind 재설치 vs shadcn/ui의 유용성 비교해보시고 더 나은 선택으로 부탁드립니다.. 사용 안 하시기로 결정하셨으면 이슈 닫으셔도 되구용. 일단 지금은 mui로 구현하겠습니다.

**Comment by kimfield98** [comment]
최대한 걷어내보려고 했는데 추가된 스타일이 꽤 있어서 새로 만드는 꼴이네요 .. 따라올 버그가 무서워서 이슈 닫겠습니다🥲

**Comment by cece-09** [comment]
넹.. shadcn으로 교체 아니구 mui랑 같이 쓰거나 해도 좋을 것 같아요 ! 아무쪼록 빠른 쪽으로,,
